# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing
services:
  find-ffa-frontend:
    build:
      target: development
    image: find-ffa-frontend-development
    container_name: find-ffa-frontend-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
      - ./.env:/home/node/.env
